[package]
name = "vcg"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Utilities for manipulating verification conditions."
repository = "https://github.com/DavePearce/VcGen"
